### ISSUE TITLE
Eval question

### ISSUE THREAD

**Issue by xjcvip007** [yongliang-wu/NumPro#4]
![图片](https://github.com/user-attachments/assets/69d7c485-f326-4ced-9c87-83982d6520ce)
Thanks for amazing job~ One question, how do you use Gpt4o and qwen2-vl for video input testing? Don't they only support single-frame image inputs?

**Comment by yongliang-wu** [comment]
Thank you for asking.

GPT-4o now supports multi-frame input. You can refer to the guides [here](https://platform.openai.com/docs/guides/vision).

![Image](https://github.com/user-attachments/assets/5d261709-2b3b-48b7-a367-d903abda6417)

Additionally, check out Qwen-2VL-7B [here](https://github.com/QwenLM/Qwen2-VL).

![Image](https://github.com/user-attachments/assets/1bdc9180-0217-45ca-89ad-3747f718392c)
