### ISSUE TITLE
Question about the performance of numpro_ft on Charades dataset

### ISSUE THREAD

**Issue by hzsun1995** [yongliang-wu/NumPro#5]
Hi,

Thank you for sharing your excellent work and providing the numpro_ft model. 

I recently experimented with the numpro_ft model on the Charades dataset following the instructions in your repository. However, I was unable to reproduce the results reported in the paper.I achieved the following metrics:

- R@0.3: 30.48
- R@0.5: 10.19
- R@0.7: 2.63
- mIoU: 20.49

These are significantly lower than the performance reported in the paper. Could you kindly confirm if the provided checkpoint files are correct? Or is there any additional step required to achieve the reported results?

I would greatly appreciate your guidance on this matter. Thank you again for your amazing work!

**Comment by yongliang-wu** [comment]
What's your sampling rate during inference? I use 0.5 FPS during the experiment of NumPro-FT, so all results should be x2 to align with the GT.
